# Generated by Django 4.2 on 2023-08-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.JSONField()),
                ('calendar_data', models.JSONField(default=dict)),
                ('subscription_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
