MESSAGE_STATUS_QUEUED = "QUEUED"
MESSAGE_STATUS_SENT = "SENT"
MESSAGE_STATUS_FAILED = "FAILED"
MESSAGE_STATUS_CANCELLED = "CANCELLED"
MESSAGE_STATUS_SKIPPED = "SKIPPED"

MESSAGE_STATUS_CHOICES = [
    (MESSAGE_STATUS_QUEUED, MESSAGE_STATUS_QUEUED),
    (MESSAGE_STATUS_SENT, MESSAGE_STATUS_SENT),
    (MESSAGE_STATUS_FAILED, MESSAGE_STATUS_FAILED),
    (MESSAGE_STATUS_CANCELLED, MESSAGE_STATUS_CANCELLED),
    (MESSAGE_STATUS_SKIPPED, MESSAGE_STATUS_SKIPPED),
]
