version: '3.9'

volumes:
  prismvio_local_postgres_data: {}
  prismvio_local_postgres_data_backups: {}
  prismvio_local_elasticsearch_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: prismvio_local_django
    container_name: prismvio_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: prismvio_production_postgres
    container_name: prismvio_local_postgres
    volumes:
      - prismvio_local_postgres_data:/var/lib/postgresql/data
      - prismvio_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  docs:
    image: prismvio_local_docs
    container_name: prismvio_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./prismvio:/app/prismvio:z
    ports:
      - '9000:9000'
    command: /start-docs

  redis:
    image: redis:6
    container_name: prismvio_local_redis
    ports:
      - '6379:6379'

  celeryworker:
    <<: *django
    image: prismvio_local_celeryworker
    container_name: prismvio_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: prismvio_local_celerybeat
    container_name: prismvio_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: prismvio_local_flower
    container_name: prismvio_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  elasticsearch:
    container_name: prismvio_local_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - prismvio_local_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - es-net
    environment:
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      network.host: "0.0.0.0"
      bootstrap.memory_lock: "true"


  kibana:
    container_name: prismvio_local_kibana
    image: docker.elastic.co/kibana/kibana:8.10.1
    environment:
      - ELASTICSEARCH_HOSTS=http://prismvio_local_elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - es-net

networks:
  es-net:
    driver: bridge