version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  redis_data: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: prismvio_production_django
    volumes:
      - production_django_media:/app/prismvio/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: prismvio_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

  celeryworker:
    <<: *django
    image: prismvio_production_celeryworker
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    image: prismvio_production_celerybeat
    command: /start-celerybeat
    ports: []

  flower:
    <<: *django
    image: prismvio_production_flower
    command: /start-flower
    ports:
      - "5555:5555"
