# Generated by Django 4.2.5 on 2023-09-28 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, default=list, null=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ("event_data", models.JSONField(blank=True, default=dict, null=True)),
                ("merchant_id", models.IntegerField(blank=True, null=True)),
                ("staff_id", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
