# Generated by Django 4.2.5 on 2023-09-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
