# Generated by Django 4.2.5 on 2023-09-20 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu_merchant", "0001_initial"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, default=None, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=45, null=True)),
                ("country_code", models.CharField(blank=True, max_length=4, null=True)),
                ("country_number", models.CharField(blank=True, max_length=4, null=True)),
                ("platform_number", models.CharField(blank=True, max_length=45, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("timezone", timezone_field.fields.TimeZoneField(blank=True, default="Asia/Ho_Chi_Minh", null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("VND", "Vnd"), ("USD", "Usd"), ("EUR", "Eur")],
                        default="VND",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("uid", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staffs_visible", models.BooleanField(default=True)),
                ("total_available_slot", models.IntegerField(blank=True, default=0, null=True)),
                ("total_available_slots_unit", models.CharField(blank=True, max_length=45, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, related_name="merchants", to="menu_merchant.category"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="connect with country in table country location",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.country",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        help_text="connect with District in table District location",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.district",
                    ),
                ),
                ("hashtag", models.ManyToManyField(blank=True, related_name="merchants", to="menu_merchant.hashtag")),
                ("keyword", models.ManyToManyField(blank=True, related_name="merchants", to="menu_merchant.keyword")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        help_text="connect with Province in table Province location",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.province",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        help_text="connect with Ward in table Ward location",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.ward",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeslotCollectionMerchant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekly", models.JSONField(blank=True, default=list, null=True)),
                ("daily", models.JSONField(blank=True, default=list, null=True)),
                ("shifts", models.JSONField(blank=True, default=list, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslotcollection",
                        to="merchant.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExclusionDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("dates", models.JSONField(blank=True, default=list, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusion_date",
                        to="merchant.merchant",
                    ),
                ),
            ],
        ),
    ]
