# Generated by Django 4.2.5 on 2023-09-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
