# Generated by Django 4.2.5 on 2023-09-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_merchant", "0007_keyword_rename_parent_id_category_parent_and_more"),
        ("merchant", "0002_alter_merchant_created_at_alter_merchant_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="merchants", to="menu_merchant.category"),
        ),
        migrations.AddField(
            model_name="merchant",
            name="keyword",
            field=models.ManyToManyField(blank=True, related_name="merchants", to="menu_merchant.keyword"),
        ),
    ]
