# Generated by Django 4.2.5 on 2023-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_merchant", "0008_remove_products_keyword_remove_services_keyword_and_more"),
        ("merchant", "0003_merchant_categories_merchant_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="hashtag",
            field=models.ManyToManyField(blank=True, related_name="merchants", to="menu_merchant.hashtag"),
        ),
    ]
