# Generated by Django 4.2.5 on 2023-09-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0003_merchant_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="allow_staff_connect_user",
            field=models.BooleanField(default=False),
        ),
    ]
