# Generated by Django 4.2.5 on 2023-09-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0003_rename_hashtag_merchant_hashtags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="opening_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
