# Generated by Django 4.2.5 on 2023-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0004_merchant_allow_staff_connect_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
