# Generated by Django 4.2.5 on 2023-09-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
        ("merchant", "0004_merchant_hashtag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="merchant",
            old_name="location",
            new_name="address",
        ),
        migrations.AddField(
            model_name="merchant",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="connect with country in table country location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.country",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="district",
            field=models.ForeignKey(
                blank=True,
                help_text="connect with District in table District location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.district",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="province",
            field=models.ForeignKey(
                blank=True,
                help_text="connect with Province in table Province location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.province",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                help_text="connect with Ward in table Ward location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.ward",
            ),
        ),
    ]
