# Generated by Django 4.2.5 on 2023-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0004_merchant_opening_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="avatar",
            field=models.JSONField(blank=True, default=dict, help_text="Avatar of merchant vio app", null=True),
        ),
        migrations.AddField(
            model_name="merchant",
            name="banner",
            field=models.JSONField(blank=True, default=dict, help_text="Banner", null=True),
        ),
    ]
