# Generated by Django 4.2.5 on 2023-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0005_alter_merchant_latitude_alter_merchant_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
