# Generated by Django 4.2.5 on 2023-10-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0007_alter_merchant_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="description_html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
