# Generated by Django 4.2 on 2023-09-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, null=True, verbose_name='Celery task id')),
                ('exec_time', models.FloatField(max_length=50, null=True, verbose_name='Execution_time')),
                ('task_name', models.CharField(db_index=True, help_text='Name of the Task which was run', max_length=255, null=True, verbose_name='Task Name')),
                ('status', models.CharField(db_index=True, default='PENDING', help_text='Current state of the task being run', max_length=20, verbose_name='Task State')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, help_text='Datetime field when the task was updated in UTC', verbose_name='Last updated DateTime')),
                ('traceback', models.TextField(blank=True, help_text='Text of the traceback if the task generated one', null=True, verbose_name='Traceback')),
                ('meta', models.JSONField(default=None, editable=False, help_text='JSON meta information about the task, such as information on child tasks', null=True, verbose_name='Task Meta Information')),
            ],
        ),
    ]
