# Generated by Django 4.2.5 on 2023-09-26 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("verb", models.CharField(max_length=100)),
                ("topic", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("content", models.CharField(blank=True, max_length=250, null=True)),
                ("template", models.CharField(blank=True, help_text="Message template", max_length=250, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        default="SENT",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                ("visible", models.BooleanField(default=True, help_text="Visible to user?")),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("memo", models.CharField(blank=True, help_text="Internal Notes", max_length=250, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_object",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "indexes": [
                    models.Index(fields=["user"], name="notificatio_user_id_a25fc0_idx"),
                    models.Index(fields=["created_at"], name="notificatio_created_5a3e36_idx"),
                    models.Index(fields=["user", "visible"], name="notificatio_user_id_4aa930_idx"),
                ],
            },
        ),
    ]
