# Generated by Django 4.2.5 on 2023-09-21 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("menu_merchant", "0001_initial"),
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="merchant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="service", to="merchant.merchant"
            ),
        ),
    ]
