# Generated by Django 4.2.5 on 2023-09-26 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchant", "0001_initial"),
        ("menu_merchant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="merchant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="services", to="merchant.merchant"
            ),
        ),
    ]
