# Generated by Django 4.2.5 on 2023-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_merchant", "0003_alter_promotion_created_at_alter_promotion_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="products",
            field=models.ManyToManyField(null=True, related_name="promotions", to="menu_merchant.products"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="services",
            field=models.ManyToManyField(null=True, related_name="promotions", to="menu_merchant.services"),
        ),
    ]
