# Generated by Django 4.2.5 on 2023-09-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_merchant", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
