# Generated by Django 4.2.5 on 2023-09-13 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0001_initial"),
        ("menu_merchant", "0004_alter_promotion_products_alter_promotion_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion",
                to="merchant.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="products",
            field=models.ManyToManyField(related_name="promotions", to="menu_merchant.products"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="services",
            field=models.ManyToManyField(related_name="promotions", to="menu_merchant.services"),
        ),
    ]
