# Generated by Django 4.2.5 on 2023-09-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu_merchant", "0006_alter_products_category_alter_products_merchant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="category",
            old_name="parent_id",
            new_name="parent",
        ),
        migrations.AddField(
            model_name="category",
            name="hashtag",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="menu_merchant.hashtag",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="keyword",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="menu_merchant.keyword",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="keyword",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service",
                to="menu_merchant.keyword",
            ),
        ),
    ]
