# Generated by Django 4.2.5 on 2023-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_merchant", "0007_keyword_rename_parent_id_category_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="services",
            name="keyword",
        ),
        migrations.AddField(
            model_name="products",
            name="keyword",
            field=models.ManyToManyField(blank=True, related_name="products", to="menu_merchant.keyword"),
        ),
        migrations.AddField(
            model_name="services",
            name="keyword",
            field=models.ManyToManyField(blank=True, related_name="service", to="menu_merchant.keyword"),
        ),
    ]
