# Generated by Django 4.2.5 on 2023-09-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_merchant", "0008_remove_products_keyword_remove_services_keyword_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="images",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
