# Generated by Django 4.2.5 on 2023-09-06 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import prismvio.users.managers
import users.enums


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("username", models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ("verified_email_at", models.DateTimeField(blank=True, null=True, verbose_name="Verified Email")),
                (
                    "verified_phone_number_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Verified Phone Number"),
                ),
                ("first_name", models.CharField(blank=True, max_length=45, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=45, null=True)),
                ("last_name", models.CharField(blank=True, max_length=45, null=True)),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Influencer", "Influencer"),
                            ("Partner", "Partner"),
                            ("User", "User"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female"), ("Others", "Others")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("MR", "Married"),
                            ("SI", "Single"),
                            ("SE", "Separated"),
                            ("DV", "Divorce"),
                            ("OT", "Others"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("business_admin", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", prismvio.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserSocialAuth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=32)),
                ("uid", models.CharField(blank=True, max_length=255, null=True)),
                ("extra_data", models.JSONField()),
                ("calendar_data", models.JSONField(default=dict)),
                ("subscription_id", models.CharField(db_index=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OneTimePassword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ("signature", models.CharField(db_index=True, max_length=32)),
                ("send_counter", models.PositiveSmallIntegerField(default=0)),
                ("last_send", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_counter", models.PositiveSmallIntegerField(default=0)),
                ("last_check", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "otp_type",
                    models.CharField(db_index=True, default=users.enums.OTPType["PHONE_NUMBER"], max_length=30),
                ),
                (
                    "otp_action",
                    models.CharField(db_index=True, default=users.enums.OTPAction["ID_VERIFICATION"], max_length=30),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
