# Generated by Django 4.2.5 on 2023-09-13 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar_user_country_code_user_country_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
