# Generated by Django 4.2.5 on 2023-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_friend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_address",
        ),
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
