# Generated by Django 4.2.5 on 2023-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_full_address_alter_user_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
