# Generated by Django 4.2.5 on 2023-09-22 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_avatar"),
        ("users", "0003_alter_user_avatar_privacysetting_friendship"),
    ]

    operations = []
