# Generated by Django 4.2.5 on 2023-09-21 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_delete_usersocialauth"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacySetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "username_privacy",
                    models.CharField(
                        choices=[("OM", "Only Me"), ("EV", "Everyone"), ("FR", "Friends")], default="EV", max_length=2
                    ),
                ),
                (
                    "email_privacy",
                    models.CharField(
                        choices=[("OM", "Only Me"), ("EV", "Everyone"), ("FR", "Friends")], default="EV", max_length=2
                    ),
                ),
                (
                    "phone_number_privacy",
                    models.CharField(
                        choices=[("OM", "Only Me"), ("EV", "Everyone"), ("FR", "Friends")], default="EV", max_length=2
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PE", "Pending"), ("AC", "Accepted"), ("DE", "Declined")], default="PE", max_length=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="friend recipient",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="the person sending the friend request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
