# Generated by Django 4.2.5 on 2023-09-26 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booked_by",
        ),
    ]
