# Generated by Django 4.2.5 on 2023-09-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("bookings", "0003_booking_merchant_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingservice",
            name="booked_user_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booked_user_events",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="merchant_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merchant_events",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="staff_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_events",
                to="events.event",
            ),
        ),
    ]
